---
title: Optimal management of a stochastically varying population when policy adjustment is costly
author: 
  - name: Carl Boettiger
    affiliation: cstar
    email: cboettig (at) gmail.com
    footnote: Corresponding author
  - name: Michael Bode
    affiliation: melbourne
  - name: James Sanchirico
    affiliation: UCD
  - name: Jacob LaRiviere
    affiliation: UTK
  - name: Alan Hastings
    affiliation: UCD
  - name: Paul Armsworth 
    affiliation: UTK

address: 
  - code: cstar
    address: | 
      Center for Stock Assessment Research,
      110 Shaffer Rd,
      Santa Cruz, CA 95050, USA 
  - code: UCD
    address: Department of Environmental Science and Policy, University of California, Davis
  - code: melbourne
    address: University of Melbourne, Australia 
  - code: UTK
    address: University of Tennessee, Knoxville


layout: review,12pt
linenumbers: true


bibliography: components/references.bib
csl: components/ecology.csl
documentclass: components/elsarticle

output:
  pdf_document:
    template: components/elsarticle.latex
    fig_caption: true

---



```{r configure, include=FALSE, cache=FALSE}
#source("components/install.R")

library("methods")
library("knitr")
basename <- "supplement"
opts_chunk$set(fig.path = paste("components/figure/", basename, "-", sep=""),
               cache.path = paste("components/cache/", basename, "/", sep=""))
opts_chunk$set(cache = 2)
opts_chunk$set(tidy=FALSE, warning=FALSE, message=FALSE, 
               comment = NA, verbose = TRUE, echo=FALSE)
# PDF-based figures
opts_chunk$set(dev='pdf')
fig.cache <- TRUE

library("rmarkdown")
library("pdgControl")
library("reshape2")
library("plyr")
library("ggplot2")
library("data.table")
library("pander")
library("cboettigR")
library("ggthemes")
library("snowfall")
library("tidyr")
library("dplyr")
transparent = theme(
    panel.background = element_rect(fill = "transparent",colour = NA), 
    plot.background = element_rect(fill = "transparent",colour = NA))

theme_set(theme_bw(base_size=18) + transparent)
```

```{r analysis, include=FALSE}
source("components/supp_analysis.R")
```



```{r ex_fish, fig.cap="", dev=c("pdf", "svg", "png"), dev.args=list(bg="transparent")}
ex <- filter(dt, replicate=="rep_17" & penalty_fn == "L1" & time < 20)
ggplot(ex) + 
  geom_line(aes(time, fishstock), col="darkblue", lwd=1)
```



## So then, do our optimal policies

```{r ex_harvest, fig.cap="", dev=c("pdf", "svg", "png"), dependson="ex_fish", dev.args=list(bg="transparent")}
ggplot(ex) + 
  geom_line(aes(time, harvest_alt), col="darkgreen", lwd=1) +
  ylab("Optimal quota policy") 
```


```{r, fig.cap="",  dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent"), fig.height=3}
ex <- dt %>% 
  filter(replicate=="rep_17" & penalty_fn == "L1" & time < 20) %>%
  select(time, fishstock, harvest_alt) %>%
  gather(variable, stock, -time) 
ggplot(ex) + 
  geom_line(aes(time, stock, col=variable), lwd=1) + 
  scale_color_discrete(labels=c(fishstock = "Stock size", harvest_alt = "Harvest policy"), name="") 

```

Apples to Apples
------------------

```{r Figure_2, fig.cap="",  dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}

relabel <- c(L1 = substitute(paste(Pi[1])),
             L2 = substitute(paste(Pi[2])),
             fixed = substitute(paste(Pi[3])))

ggplot(fees, aes(c2, (npv0-value)/npv0, color=variable)) + 
  geom_line(lwd=1) + 
  geom_hline(aes(yintercept=reduction), linetype=4) + 
  xlab("Penalty coefficient") +
  ylab("Reduction in net present value") + 
  scale_color_discrete(labels=relabel) 


```


```{r reex, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent"), fig.height=3}
ggplot(ex) + 
  geom_line(aes(time, stock, col=variable), lwd=1) + 
  scale_color_discrete(labels=c(fishstock = "Stock size", harvest_alt = "Harvest policy"), name="") 
```


Quadratic Costs ($\Pi_2$)
-------------------------

```{r quadratic, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}
ex <- dt %>% 
  filter(replicate=="rep_17" & penalty_fn == "L2") %>%
  select(time, harvest, harvest_alt) %>%
  gather(variable, value, -time) 
ggplot(ex) + 
  geom_line(aes(time, value, col=variable), lwd=1) + 
  ylab("harvest quota") +
  scale_color_discrete(labels=c(harvest = "adjusted policy", harvest_alt = "baseline policy"), name="") 
```

Fixed Costs ($\Pi_3$)
---------------------

```{r fixed, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}
ex <- dt %>% 
  filter(replicate=="rep_17" & penalty_fn == "fixed") %>%
  select(time, harvest, harvest_alt) %>%
  gather(variable, value, -time) 
ggplot(ex) + 
  geom_line(aes(time, value, col=variable), lwd=1) + 
  ylab("harvest quota") +
  scale_color_discrete(labels=c(harvest = "adjusted policy", harvest_alt = "baseline policy"), name="") 
```

Linear Costs ($\Pi_1$)
---------------------

```{r linear, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}
ex <- dt %>% 
  filter(replicate=="rep_17" & penalty_fn == "L1") %>%
  select(time, harvest, harvest_alt) %>%
  gather(variable, value, -time) 
ggplot(ex) + 
  geom_line(aes(time, value, col=variable), lwd=1) + 
  ylab("harvest quota") +
  scale_color_discrete(labels=c(harvest = "adjusted policy", harvest_alt = "baseline policy"), name="") 
```



(For comparison)
----------------

```{r Figure_3, dependson="tidy", fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}

fig3_df <- as.data.frame(subset(dt, replicate=='rep_17'))
fig3_df <- fig3_df[c("time", "fishstock", "alternate", "harvest", "harvest_alt", "penalty_fn")]
fig3_df <- melt(fig3_df, id = c("time", "penalty_fn"))
fig3_df <- data.frame(fig3_df, baseline = fig3_df$variable)
variable_map <- c(fishstock = "fish_stock", alternate = "fish_stock", harvest = "harvest", harvest_alt = "harvest")
baseline_map <- c(fishstock = "penalty", alternate = "no_penalty", harvest = "penalty", harvest_alt = "no_penalty")
fig3_df$variable <- variable_map[fig3_df$variable]
fig3_df$baseline <- baseline_map[fig3_df$baseline]

harvest_fig3 <- subset(fig3_df, variable=="harvest")
fishstock_fig3 <- subset(fig3_df, variable=="fish_stock")

labeller <- function(variable,value){
    relabel[paste(value)]
}

ggplot(harvest_fig3, aes(time, value, col=baseline)) +
  geom_line(lwd=1) +
  facet_grid(penalty_fn~., labeller = labeller) + 
  labs(x="time", y="stock size", title = "Example Harvest Dynamics")  +
  scale_color_discrete(labels=c("Reed solution", "With penalty"), name="")
```




## General trends

```{r Figure_4, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}
ggplot(subset(figure4_df, statistic != "cross.correlation"), 
       aes(penalty_fraction, value, fill=penalty_fn, col=penalty_fn))  +
  stat_summary(fun.y = mean, 
               fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom = "ribbon", alpha=0.3, colour=NA) +
  stat_summary(fun.y = mean, geom = "line") + 
  coord_cartesian(xlim = c(0, .3)) + 
  facet_wrap(~ timeseries + statistic, scale="free_y") + 
  scale_color_discrete(labels=relabel, name="Penalty function") + 
  scale_fill_discrete(labels=relabel, name="Penalty function") + 
  xlab("Penalty size (as fraction of NPV0)")
```

- Quadratic ($\Pi_2$) smooths, Linear ($\Pi_1$) flattens, Fixed ($\Pi_3$) jumps 



Consequences of policy adjustment costs 
---------------------------------------

```{r histogram-calc}
profits <- dt[, sum(profit_fishing), by=c('penalty_fn', 'replicate') ]
costs <- dt[, sum(policy_cost), by=c('penalty_fn', 'replicate') ]
reed_profits <- dt[, sum(profit_fishing_alt), by=c('penalty_fn', 'replicate') ]
reed_costs <- dt[, sum(policy_cost_alt), by=c('penalty_fn', 'replicate') ]
setnames(profits, "V1", "profits")
setnames(reed_profits, "V1", "profits")
Reed <- cbind(reed_profits, costs = reed_costs$V1, Assumption = "Reed") 
Adj <- cbind(profits, costs = costs$V1, Assumption = "Adjustment penalty")
hist_dat <- melt(rbind(Adj, Reed), id=c("penalty_fn", "replicate", "Assumption"))
````


```{r Figure_5, fig.cap="",  dependson="histogram-calc", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}

assume <- levels(as.factor(hist_dat$Assumption))
labeller <- function(variable,value){
if (variable=='penalty_fn') {
    return(relabel[paste(value)])
  } else {
    return(assume[value])
  }
}

ggplot(hist_dat) + 
  geom_density(aes(value, fill=variable, color=variable), alpha=0.8)+
  facet_grid(Assumption~penalty_fn, labeller = labeller)

```


## To say that another way:


```{r Figure_6, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}

who <- c("penalty_fn", "ignore_fraction", "assume_fraction", "reduction")
table1 <- arrange(error_df[who], reduction) 
names(table1) = c("penalty.fn", "ignoring", "assuming", "reduction")
table1_long <- melt(table1, id = c('penalty.fn', 'reduction'))
table1_long$reduction <- as.factor(table1_long$reduction)
table1_long <- subset(table1_long, reduction != "0.3")
ggplot(table1_long, aes(penalty.fn, value, fill = variable)) + 
  geom_bar(stat="identity", position="dodge") + 
  facet_wrap(~reduction, ncol=2) + 
  scale_x_discrete(labels = c('L1' = substitute(paste(Pi[1])),
                              'L2' = substitute(paste(Pi[2])),
                              'fixed' = substitute(paste(Pi[3])))) + 
  xlab("Penalty function")
```


## Mismatches are even worse:


```{r Figure_7, fig.cap="", dev=c("pdf", "svg", "png"), cache=FALSE, dev.args=list(bg="transparent")}
who <- c("penalty_fn", "ignore_fraction", "mismatched_fraction", "reduction")
table2 <- arrange(mismatches_df[who], reduction) 
names(table2) = c("penalty.fn", "ignoring", "mismatched", "reduction")
table2_long <- melt(table2, id = c('penalty.fn', 'reduction'))
table2_long$reduction <- as.factor(table2_long$reduction)

ggplot(table2_long, aes(penalty.fn, value, fill = variable)) + 
  geom_bar(stat="identity", position="dodge") + 
  facet_wrap(~reduction, scales="free_y") +
  scale_x_discrete(labels = c('L1_L2' = substitute(paste(Pi[1],"_", Pi[2])), 
                              'L2_L1' =  substitute(paste(Pi[2],"_", Pi[1])),
                              'L1_fixed' = substitute(paste(Pi[1],"_", Pi[3])), 
                              'fixed_L1' =  substitute(paste(Pi[3],"_", Pi[1])),
                              'fixed_L2' = substitute(paste(Pi[3],"_", Pi[2])), 
                              'L2_fixed' =  substitute(paste(Pi[2],"_", Pi[3])))) + 
  xlab("Penalty function as: assumed_reality") + theme_tufte(base_size=14)
```



