

```{r}
require(pdgControl)
require(reshape2)
require(ggplot2)
require(data.table)
rm(list=ls())

delta <- 0.05               # economic discounting rate
OptTime <- 20               # stopping time
gridsize <- 50              # grid size for fish stock and harvest rate (discretized population)
reward <- 0                 # bonus for satisfying the boundary condition
z_g <- function() rlnorm(1,  0, sigma_g) # mean 1
z_m <- function() 1         # No measurement noise, 
z_i <- function() 1         # No implemenation noise
f <- BevHolt                # Select the state equation
pars <- c(1.5, 0.05)        # parameters for the state equation
K <- (pars[1] - 1)/pars[2]  # Carrying capacity (for reference 
xT <- 0                     # boundary conditions
x0 <- K
x_grid <- seq(0.01, 1.2 * K, length = gridsize)  
h_grid <- seq(0.01, 0.8 * K, length = gridsize)  
```


With profits linear in price (no cost)

```{r}
profit <- profit_harvest(price = 1, c0 = 0, c1 = 0)

sigma_g <- 0.03
SDP_Mat <- determine_SDP_matrix(f, pars, x_grid, h_grid, sigma_g )
opt <- find_dp_optim(SDP_Mat, x_grid, h_grid, OptTime, xT, 
                     profit, delta, reward=reward)

p1 <- opt$D[,1]
p1 = sapply(1:length(p1), function(x) p1)
#s_opt <- value_iteration(SDP_Mat, x_grid, h_grid, OptTime=1000, xT, profit, delta)

tmp <- lapply(1:100, function(i){ 
  set.seed(i)
  ForwardSimulate(f, pars, x_grid, h_grid, x0=K, opt$D, z_g, z_m, z_i)
  })
tmp <- melt(tmp, id = names(tmp[[1]]))




sigma_g <- 0.1
SDP_Mat <- determine_SDP_matrix(f, pars, x_grid, h_grid, sigma_g )
opt <- find_dp_optim(SDP_Mat, x_grid, h_grid, OptTime, xT, 
                     profit, delta, reward=reward)

p2 <- opt$D[,1]
p2 = sapply(1:length(p2), function(x) p2)

tmp2 <- lapply(1:100, function(i){ 
  set.seed(i)
  ForwardSimulate(f, pars, x_grid, h_grid, x0=K, p2, z_g, z_m, z_i)
  })
tmp2 <- melt(tmp2, id = names(tmp2[[1]]))


tmp <- data.table(tmp)
tmp2 <- data.table(tmp2)


discounted = tmp[, sum(profit/((1+delta)^time)), by=L1]$V1
profit = tmp[, sum(profit), by=L1]$V1
#ggplot(tmp, aes(time, fishstock, group=L1)) + geom_line(alpha=0.1)
#ggplot(tmp2, aes(time, fishstock, group=L1)) + geom_line(alpha=0.1)
```

The control strategies are identical but the net present values differ.  

```{r}
identical(p1,p2)


c(low_noise = sum(tmp$profit), high_noise = sum(tmp2$profit))
```


